twice = ('Tzuyu', 'Momo', 'Sana', 'Nayeon', 'Jeongyon', 'Jihyo', 'Mina', 'Chaeyoung', 'Dahyun')
print(f'As 5 primeira integrantes são{twice[0:5]}')
print(f'As 4 ultimas integrantes são {twice[5:]}')
print(f'O nome delas em ordem alfabetica fica: {sorted(twice)}')
print(f'Nayeon é minha preferida e esta na posição {twice.index('Nayeon')} :3 ')