a = input('digite algo: ')
print('o tipo desse valor é', type(a))
print('esta capitalizado? ', a.istitle())
print('tem espaços? ', a.isspace())
print('esta em maiusculo? ', a.isupper())
print('esta em minusculo?', a.islower())
print('é alfanumerico? ', a.isalnum())
print('é um numero? ', a.isdigit())
print('é alfabetico? ', a.isalpha())
print('é decimal? ', a.isdecimal())
print('é pritavel? ',a.isprintable())
print('é uma subclasse? ', a.__init_subclass__())